---
# cSpell:disable
# Copied from: rasa/dotfiles/.github/.cspell/overrides.yml
# EDIT THE ABOVE FILE OR YOUR CHANGES WILL BE LOST!

# Manually curated list of paths/files to not spellcheck
# ignorePaths:
#   - path/to/file1
#   - path/to/file2

# Manually curated list of words to treat as incorrectly spelled
# flagWords:
#   - notaword1
#   - notaword2
