---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
# DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS:
  - BASH_EXEC  # @TODO fix BASH_EXEC issues before enabling:
  # - BASH_SHELLCHECK
  # - BASH_SHFMT
  - COPYPASTE_JSCPD
  - POWERSHELL_POWERSHELL  # Upstream code
  - SPELL_CSPELL # insanely noisy
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
EMAIL_REPORTER_EMAIL: rasa7777@gmail.com
FILEIO_REPORTER: true
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
PLUGINS:
  - https://raw.githubusercontent.com/megalinter/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml
BASH_SHELLCHECK_ARGUMENTS: '--external-sources --enable=all --exclude SC2310,SC2312'
BASH_SHFMT_ARGUMENTS: '-ci -i 2'
PRINT_ALPACA: false
# these files have comments in them, and jsonlint reject comments:
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '((.vscode|Code/User)/(extensions|keybindings|settings|Template))\.jsonc?'
