---
# cSpell:disable
# Copied from: rasa/dotfiles/.cspell/common-settings.yml
# EDIT THE ABOVE FILE, NOT THIS COPY, OR YOUR CHANGES WILL BE LOST!
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
dictionaries:
  ## cli defaults:
  # - aws
  # - bash
  # - companies
  # - computing-acronyms
  # - cryptocurrencies
  # - en_us
  # - en-common-misspellings
  # - filetypes
  # - public-licenses
  # - softwareTerms
  # - web-services
  ## vscode defaults:
  # - aws
  # - companies
  # - cryptocurrencies
  # - en_us
  # - en-common-misspellings
  # - filetypes
  # - k8s
  # - public-licenses
  # - softwareTerms
  ## overrides:
  - 'bash' # in cli, but not in vscode
  - 'computing-acronyms' # in cli, but not in vscode
  # - '!django' # icontains is misspelled on github?
  - 'docker'
  - 'html'
  - 'k8s' # in vscode, but not cli
  - 'php'
  - 'powershell' # icontains is misspelled on github?
  - 'python'
  - 'python-common'
  - 'web-services' # in cli, but not in vscode
  ## original list:
  - 'cpp'
  - 'cpp-legacy'
  # - '!csharp'
  - '!css'
  - '!fonts'
  - '!go'
  - '!golang'
  # - '!latex'
  - '!lorem-ipsum'
  - '!makefile' # missing in vscode's extension 3.0.1
  # - '!node'
  # - '!scala'
  - 'softwareTerms' # missing on GitHub?
  - '!typescript'
enableFiletypes:
  ## cli defaults:
  # - 'dart'
  # - 'fsharp'
  # - 'r'
  # - 'sql'
  # - 'svelte'
  # our overrides:
  - 'apacheconf'
  - 'autoit'
  - 'awk'
  - 'bat'
  - '!dart'
  - 'dockerfile'
  - 'editorconfig'
  - 'ignore'
  - '!fsharp'
  - '!makefile' # Added after vscode's extension's release
  - 'pip-requirements'
  - 'postscript'
  - 'powershell'
  - '!r'
  - 'reg'
  - 'shellcheckrc'
  - 'shellscript'
  - 'sql'
  - '!svelte'
enableGlobDot: true
ignorePaths:
  - '**/.git/**'
  - '**/.cspell.json'
  - '**/.cspell/**'
  - '**/*.csv'
  - '**/*.db'
  - '**/*.diff'
  - '**/*.doc'
  - '**/*.docx'
  - '**/*.json'
  - '**/*.log'
  - '**/*.lst'
  - '**/*.orig'
  - '**/*.patch'
  - '**/*.pdf'
  - '**/*.pem'
  - '**/*.ps'
  - '**/*.reg'
  - '**/*.rej'
  - '**/*.sed'
  - '**/*.tcl'
  - '**/*.tsv'
  - '**/*.wip'
  - '**/*.xls'
  - '**/*.xlsx'
  - '**/*.xml'
language: 'en'
maxNumberOfProblems: 1000
noConfigSearch: true
useGitignore: true
version: '0.2'
