---
# ~/.github/linters/.grype.yaml
# Copied from: rasa/dotfiles/.github/linters/.grype.yaml
# EDIT THE ABOVE FILE, NOT THIS COPY, OR YOUR CHANGES WILL BE LOST!
ignore:
  # selenium 4.9.1
  - vulnerability: CVE-2023-5590

# cspell:ignore grype
