---
# Copied from: rasa/dotfiles/.github/linters/actionlint.yml
# EDIT THE ABOVE FILE OR YOUR CHANGES WILL BE LOST!

# https://github.com/rhysd/actionlint/issues/424#issuecomment-2110743431
self-hosted-runner:
  labels:
    - ubuntu-24.04

paths:
  # This pattern matches any YAML file under the '.github/workflows/' directory.
  .github/workflows/**/*:
    ignore:
      # Ignore undocumented option repository_visibility.
      # PR to fix is at https://github.com/rhysd/actionlint/pull/489 .
      - 'repository_visibility'
