---
# ./.github/workflows/debug-rasa.yaml
# Copied from: rasa/dotfiles/.github/debug-rasa.yaml
# EDIT THE ABOVE FILE, NOT THIS COPY, OR YOUR CHANGES WILL BE LOST!
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json
# checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters
#   other than the build entry point and the top-level source location.
#   GitHub Actions workflow_dispatch inputs MUST be empty.

name: debug-rasa

env:
  WORKFLOW_USER: rasa
  WORKFLOW_REPO: workflows

on: # yamllint disable-line rule:truthy
  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #     - main
  workflow_call: # Required so this workflow can be called from another workflow
    inputs:
      workflow_user:
        description: "Github user name (default is 'rasa')"
        required: false
        type: string
      workflow_repo:
        description: "Github repository name (default is 'workflows')"
        required: false
        type: string
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      # checkov:skip=CKV_GHA_7
      workflow_user:
        description: "Github user name (default is 'rasa')"
        required: false
        type: string
      # checkov:skip=CKV_GHA_7
      workflow_repo:
        description: "Github repository name (default is 'workflows')"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  debug-rasa:
    name: debug-rasa
    runs-on: ubuntu-24.04

    steps:
      - name: Set workflow variables with fallback
        run: |
          echo "WORKFLOW_USER=${{ inputs.workflow_user || env.WORKFLOW_USER }}" >>"${GITHUB_ENV}"
          echo "WORKFLOW_REPO=${{ inputs.workflow_repo || env.WORKFLOW_REPO }}" >>"${GITHUB_ENV}"

      - uses: crazy-max/ghaction-dump-context@v2.3.0

