on:
  workflow_dispatch:
  schedule:
    # run every 12 hours
    - cron: '20 */12 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-2022 # was windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
        SCOOP_BRANCH: develop
